name: ci

on:
  push:
    branches:
      - main

concurrency:
  group: ci-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  run:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
          uses: actions/setup-node@v3
          with:
            node-version: '>=18'
            cache: npm

      - name: Integration
        run: |
          cd ${{ github.workspace }}
          npm ci
          npm i -D msw@latest
          npm run test

