name: ci

on:
  pull_request:
    branches:
      - main

concurrency:
  group: pr-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  run:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '>=18'
          cache: npm

      - name: Integration
        run: |
          cd ${{ github.workspace }}
          npm ci
          npm i -D msw@latest
          npm run test

